---FORMAS DE INSERTAR DATOS/AGREGAR DATOS A LAS TABLAS
--- NUMBER ONE : INDICANDO TANTO COLUMNAS COMO VALORES.
--- DBCC USEROPTIONS
--- SET DATEFORMAT TO YMD
INSERT INTO RegistroAcademicoInicial
(
Carnet, Nombres, Sexo, FechaNac, Departamento, Municipio, Email, Direccion,
Facultad, Carrera, Semestre, Turno, Asignatura, Anio, NombreProfesor, NivelAcadProf
)
VALUES
('25416812','AGUILAR RODRIGUEZ KENDALL EZEQUIEL','Masculino','2006-08-25','TIPITAPA','TIPITAPA','kendalaguilar650@gmail.com','Bo. Francisco Rojas Metasa 4c. O. MI','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO');

---NUMBER TWO
---INDICANDO SOLAMENTE LOS VALORES SIN ESPECIFAR LAS COLUMNAS
---PRIMER VALOR CAE A LA PRIMERA COLUMNA....2DO VALOR A LA SEGUNDA COLUMNA...ETC
INSERT INTO RegistroAcademicoInicial VALUES
('25416042','CORREA ESPINOZA EMELY SARAI','Femenino','2007-09-07','GRANADA','GRANADA','emelycorrea09@gmail.com','reparto madre de Dios...','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO');

---NUMBER THREE
---INSERCIONES MULTIPLES, USANDO SOLAMENTE UNA SENTENCIA INSERT Y SIN ESPECIFICAR CAMPOS.
INSERT INTO RegistroAcademicoInicial VALUES
('25414370','DIAZ ALEMAN JOSE ALEXANDER','Masculino','10/08/2007','MASAYA','MASAYA','jalexanderda2@gmail.com','Plaza Pedro Joaqu n Chamorro 5 cuadras al sur y 25 varas al sureste','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('19033517','GONZALEZ GONZALEZ KARLA JANINA','Femenino','14/09/1999','MANAGUA','MANAGUA','yanina1999gonzalez@gmail.com','Barrio healeah 2 etapa. De enel central 2 cuadras al sur, 6 cuadras abajo, 4 cuadras al sur 1 y 1/2 cuadras abajo','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25415998','LOVO ORTEGA IGNACIO DE JESUS','Masculino','21/02/2008','MASAYA','NINDIRI','snowyisthepenguin@gmail.com','Santa Ana Sur, del Sport Arena 100mts.norte 300mts.oeste','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25414997','MEDRANO DAVILA LUIS DAVID','Masculino','10/03/2008','MANAGUA','MANAGUA','medranoluis1021@gmail.com','Del tope de Villa Flor Sur 4 Cuadras al Sur, 2 1/2 Cuadras arriba','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25419507','MENA SEQUEIRA KATHERIN VANESSA','Femenino','27/06/2007','RIVAS','BELEN','katherinvanesamenasequeira@gmail.com','Cmca. San Juan Viejo Iglesia Cat lica 90mts. S.','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25405450','MIRANDA PEREZ JOSE DANIEL','Masculino','04/08/2006','MANAGUA','MANAGUA','josedanielmirandaperez410@gmail.com','BO. LA PRIMAVERA DONDE FUE SIEMENS 8C. N. 1/2C. O. 1/2C. N.','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25411686','MONTENEGRO CASTILLO ANDREA SAMANTHA','Femenino','14/04/2008','MANAGUA','MANAGUA','montenegroandreaaa@gmail.com','Km 10 y medio carretera a Masaya 2 km al sur media al este media al sur','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25411147','MU OZ MARIN PAOLA MARISOL','Femenino','09/10/2007','MANAGUA','MATEARE','jungpaola48@gmail.com','Polo D Desarrollo Canaan vivienda 1 7606 escuela de sargentos 1E MS','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25405614','OYARZO MORALES RICARDO ALBERTO','Masculino','18/07/2007','MANAGUA','MANAGUA','ricardooyarzokakaroto@gmail.com','Proyecto Bismarck Martinez: Urbanizaci n Villa esperanza de la rotonda enatrel 600 mts al sur. Bloque 1-7 lote 1140','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','BASES DE DATOS',2,'RAUL DAVILA MENIS','EMPIRICO'),
('25400246','SARRIA GARCIA ALVARO ISMAEL','Masculino','26/08/2008','MANAGUA','MANAGUA','sarriaismael07@gmail.com','Bo. Jerico Terminal 119, 5C al sur 25 varas abajo','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25416812','AGUILAR RODRIGUEZ KENDALL EZEQUIEL','Masculino','25/08/2006','TIPITAPA','TIPITAPA','kendalaguilar650@gmail.com','Bo. Francisco Rojas Metasa 4c. O. MI','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25416042','CORREA ESPINOZA EMELY SARAI','Femenino','07/09/2007','GRANADA','GRANADA','emelycorrea09@gmail.com','reparto madre de Dios C.D.I Granda 1 cuadra y media al este No.121','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25414370','DIAZ ALEMAN JOSE ALEXANDER','Masculino','10/08/2007','MASAYA','MASAYA','jalexanderda2@gmail.com','Plaza Pedro Joaqu n Chamorro 5 cuadras al sur y 25 varas al sureste','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('19033517','GONZALEZ GONZALEZ KARLA JANINA','Femenino','14/09/1999','MANAGUA','MANAGUA','yanina1999gonzalez@gmail.com','Barrio healeah 2 etapa. De enel central 2 cuadras al sur, 6 cuadras abajo, 4 cuadras al sur 1 y 1/2 cuadras abajo','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25415998','LOVO ORTEGA IGNACIO DE JESUS','Masculino','21/02/2008','MASAYA','NINDIRI','snowyisthepenguin@gmail.com','Santa Ana Sur, del Sport Arena 100mts.norte 300mts.oeste','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25414997','MEDRANO DAVILA LUIS DAVID','Masculino','10/03/2008','MANAGUA','MANAGUA','medranoluis1021@gmail.com','Del tope de Villa Flor Sur 4 Cuadras al Sur, 2 1/2 Cuadras arriba','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25419507','MENA SEQUEIRA KATHERIN VANESSA','Femenino','27/06/2007','RIVAS','BELEN','katherinvanesamenasequeira@gmail.com','Cmca. San Juan Viejo Iglesia Cat lica 90mts. S.','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25405450','MIRANDA PEREZ JOSE DANIEL','Masculino','04/08/2006','MANAGUA','MANAGUA','josedanielmirandaperez410@gmail.com','BO. LA PRIMAVERA DONDE FUE SIEMENS 8C. N. 1/2C. O. 1/2C. N.','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25411686','MONTENEGRO CASTILLO ANDREA SAMANTHA','Femenino','14/04/2008','MANAGUA','MANAGUA','montenegroandreaaa@gmail.com','Km 10 y medio carretera a Masaya 2 km al sur media al este media al sur','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25411147','MU OZ MARIN PAOLA MARISOL','Femenino','09/10/2007','MANAGUA','MATEARE','jungpaola48@gmail.com','Polo D Desarrollo Canaan vivienda 1 7606 escuela de sargentos 1E MS','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25405614','OYARZO MORALES RICARDO ALBERTO','Masculino','18/07/2007','MANAGUA','MANAGUA','ricardooyarzokakaroto@gmail.com','Proyecto Bismarck Martinez: Urbanizaci n Villa esperanza de la rotonda enatrel 600 mts al sur. Bloque 1-7 lote 1140','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25400246','SARRIA GARCIA ALVARO ISMAEL','Masculino','26/08/2008','MANAGUA','MANAGUA','sarriaismael07@gmail.com','Bo. Jerico Terminal 119, 5C al sur 25 varas abajo','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','PROGRAMACION I',2,'ROBERTO SOLIS','MAESTRIA'),
('25416812','AGUILAR RODRIGUEZ KENDALL EZEQUIEL','Masculino','25/08/2006','TIPITAPA','TIPITAPA','kendalaguilar650@gmail.com','Bo. Francisco Rojas Metasa 4c. O. MI','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25416042','CORREA ESPINOZA EMELY SARAI','Femenino','07/09/2007','GRANADA','GRANADA','emelycorrea09@gmail.com','reparto madre de Dios C.D.I Granda 1 cuadra y media al este No.121','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25414370','DIAZ ALEMAN JOSE ALEXANDER','Masculino','10/08/2007','MASAYA','MASAYA','jalexanderda2@gmail.com','Plaza Pedro Joaqu n Chamorro 5 cuadras al sur y 25 varas al sureste','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('19033517','GONZALEZ GONZALEZ KARLA JANINA','Femenino','14/09/1999','MANAGUA','MANAGUA','yanina1999gonzalez@gmail.com','Barrio healeah 2 etapa. De enel central 2 cuadras al sur, 6 cuadras abajo, 4 cuadras al sur 1 y 1/2 cuadras abajo','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25415998','LOVO ORTEGA IGNACIO DE JESUS','Masculino','21/02/2008','MASAYA','NINDIRI','snowyisthepenguin@gmail.com','Santa Ana Sur, del Sport Arena 100mts.norte 300mts.oeste','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25414997','MEDRANO DAVILA LUIS DAVID','Masculino','10/03/2008','MANAGUA','MANAGUA','medranoluis1021@gmail.com','Del tope de Villa Flor Sur 4 Cuadras al Sur, 2 1/2 Cuadras arriba','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25419507','MENA SEQUEIRA KATHERIN VANESSA','Femenino','27/06/2007','RIVAS','BELEN','katherinvanesamenasequeira@gmail.com','Cmca. San Juan Viejo Iglesia Cat lica 90mts. S.','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25405450','MIRANDA PEREZ JOSE DANIEL','Masculino','04/08/2006','MANAGUA','MANAGUA','josedanielmirandaperez410@gmail.com','BO. LA PRIMAVERA DONDE FUE SIEMENS 8C. N. 1/2C. O. 1/2C. N.','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25411686','MONTENEGRO CASTILLO ANDREA SAMANTHA','Femenino','14/04/2008','MANAGUA','MANAGUA','montenegroandreaaa@gmail.com','Km 10 y medio carretera a Masaya 2 km al sur media al este media al sur','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25411147','MU OZ MARIN PAOLA MARISOL','Femenino','09/10/2007','MANAGUA','MATEARE','jungpaola48@gmail.com','Polo D Desarrollo Canaan vivienda 1 7606 escuela de sargentos 1E MS','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25405614','OYARZO MORALES RICARDO ALBERTO','Masculino','18/07/2007','MANAGUA','MANAGUA','ricardooyarzokakaroto@gmail.com','Proyecto Bismarck Martinez: Urbanizaci n Villa esperanza de la rotonda enatrel 600 mts al sur. Bloque 1-7 lote 1140','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA'),
('25400246','SARRIA GARCIA ALVARO ISMAEL','Masculino','26/08/2008','MANAGUA','MANAGUA','sarriaismael07@gmail.com','Bo. Jerico Terminal 119, 5C al sur 25 varas abajo','CIENCIAS BASICAS Y TEC.','CIENCIA DE DATOS','II','Matutino','ESTADISTICA I',2,'DIANA HERNANDEZ','LICENCIADA')
